### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by nilmali**
Sagar Sir I have added style tag in the head section and added div tag in body. Kindly check on it and approve my request.

### CODE REVIEW

**Comment by nilmali** [comment]
Sagara Approve mado kano

**Comment by nilmali** [comment]
@sainiranjan024 @Harsha3274 - Good Afternoon Sir, Please follow the updated code and consider my request for the contribution of the code, Kindly check on it.

**Review by Harsha3274 — APPROVED** [review]
good work keep it up

**Review by sainiranjan024 — APPROVED** [review]
hi nilesh  try to work hard

**Comment by nilmali** [comment]
> hi nilesh try to work hard

Niranjan u better leave this repository and fuck off

**Comment by nilmali** [comment]
> good work keep it up

Thank you Harsha proud to be in your team

**Pull request merged**
